### ISSUE TITLE
[High Priority] Drive Motor Controller Interface

### ISSUE THREAD

**Issue by SwapnilPande** [vanderbiltrobotics/NASA-RMC-2018-2019#1]
**Which section of robot code is this for?**
Drive Control

**Description of feature**
* Develop kinematic model to convert drive commands to motor velocities
* Develop ROS Node to translate drive commands to motor controller commands for the drive motors.

**Comment by partlygloudy** [comment]
Good work guys, I'll look through your progress and have some suggestions for next steps at Thursday's meeting

**Comment by Chinchuluun1029** [comment]
Haven't done much. Currently just learning how to use rospy, the whole environment is set up and can be run. Just need to know how to implement the functions.

**Comment by llblanc64** [comment]
Connected all the publishers and subscribers with (hopefully) the correct message types after the conversion math. The math for linear/angular velocities might be somewhat wrong, though. Also trying to learn ros and python syntax more deeply.

**Comment by acarsgithub** [comment]
Getting more familiar with the python syntax and libraries and i rewrote some old code from last year from c++ into python. Also, we have the math figured out partially for linear and angular velocities of the motors, may need to account for more stuff though. I'm trying to understand ros more deeply.

**Comment by partlygloudy** [comment]
I think the math is working here now, there was one small division issue but otherwise it works as expected.  So the main functionality of this node is finished. Next step is to read the wheel radius and wheel separation from the parameter server and pass those into the function, rather than hard coding them

Names for the parameters:
"wheel_radius"
"wheel_base_separation"

**Comment by partlygloudy** [comment]
Made a few additions:
1. Added the ability to publish pwm values rather than motor speeds - the mode used can be configured using a parameter
2. Node now has 4 publishers which each publish a float value for a single motor. This is the way the motor_control interface is set up
3. Added the ability to remap the input velocities to a desired output range. This is important mainly for teleop control - the joystick node will output velocities in the range -1.0 to 1.0 which won't be the range we want to be commanding velocities in. Remapping allows us to choose any output range we want without having to mess with the joystick node output
4. Added parameters for configuring all the aforementioned features

Next steps:
- Write a launch file or launch files that have the parameters set as we would want them for common use cases
- Test the new additions to the code and make sure they work as expected

After those tasks are done, I think this issue should be just about done

**Comment by partlygloudy** [comment]
I can't think of any obvious improvements to what we've got right now and the current version works as expected. Going to close the issue now.
